name: 'Build and upload wheel'
description: 'Build with cibuildwheel, test and upload to github releases'
inputs:
  gh_token:
    description: 'Github token used to upload the wheels'
    required: true
  test_pypi_token:
    description: 'Test Pypy token used to test the publish release'
    required: true
  upload:
    description: 'Upload the wheels packages to github release'
    type: boolean
    required: false
    default: false
runs:
  using: 'composite'    
  steps:
  - name: Run mypy
    run: mypy --install-types --non-interactive --ignore-missing-imports .
    shell: bash
      
  - name: Build wheels
    env:
      CIBW_BUILD: "*-manylinux_x86_64 *-manylinux_aarch64 *-macosx_x86_64 *-macosx_arm64"
      CIBW_SKIP: cp311-*
    run: python3 -m cibuildwheel --output-dir wheelhouse
    shell: bash

  - name: test wheel
    run: |
      pip3 install wheelhouse/*-$(python3 -c "from sys import version_info as v; print(f'cp{v.major}{v.minor}');")*manylinux*x86_64*.whl
      test-${{ github.event.repository.name }}
    shell: bash

  - name: Publish to testpypi
    if: inputs.upload == 'true'
    run: twine upload --skip-existing -r testpypi -u __token__ -p ${{ inputs.test_pypi_token }} wheelhouse/*.whl
    shell: bash

  - name: Fix permissions for repository directory
    if: inputs.upload == 'true'
    run: git config --global --add safe.directory /__w/${{ github.event.repository.name }}/${{ github.event.repository.name }}
    shell: bash

  - name: Upload wheels
    if: inputs.upload == 'true'
    env:
      GH_TOKEN: ${{ inputs.gh_token }}
    run: gh release upload v$(cat VERSION) ./wheelhouse/*.whl --clobber
    shell: bash
