name: 'Utility action'
description: 'Check if the PR is intended for release. Format code with clang linter and commit the changes.'
inputs:
  gh_token:
    description: 'Github token used to check release'
    required: true
  utility_token:
    description: 'Github token used to commit the changes'
    required: true
  ci_token:
    description: 'Github token of fm-ci-bot'
    required: true
outputs:
  release-check:
    description: 'Boolean to check if the PR is a release'
    value: ${{ steps.release-check.outputs.release }}
runs:
  using: 'composite'    
  steps:
  - uses: actions/checkout@main
    with: 
      fetch-depth: 0

  # Install python wrappers for gh
  - name: Install PyGitHub
    run: pip3 install PyGithub
    shell: bash
    
  - uses: de-vri-es/setup-git-credentials@v2
    with:
      credentials: https://fm-ci-bot:${{ inputs.ci_token }}@github.com/

  - name: Check curr dir
    run: ls -las
    shell: bash

  - name: Check action path ${{github.action_path}}
    working-directory: ${{github.action_path}}
    run: ls -las
    shell: bash

  # Detect release
  - name: Check if PR is release
    id: release-check
    working-directory: ${{github.action_path}}
    env: 
      GH_TOKEN: ${{ inputs.gh_token }}
      GIT_MERGE_BASE: ${{ github.base_ref }}
      GIT_MERGE_HEAD: ${{ github.head_ref }}
      GIT_MERGE_COMMIT: ${{ github.sha }}
      GIT_REPO: ${{ github.repository }}
    run: python3 versioncheck
    shell: bash

  # Code formatting with Clang linter
  - uses: DoozyX/clang-format-lint-action@v0.14
    with:
      source: '.'
      extensions: 'h,c,hpp,cpp'
      clangFormatVersion: 14
      inplace: True

  # Commit clang-format changes
  - uses: EndBug/add-and-commit@v4
    with:
        author_name: CI bot
        author_email: dev@featuremine.com
        message: 'Committing clang-format changes'
    env:
      GITHUB_TOKEN: ${{ inputs.utility_token }}
