# COPYRIGHT (c) 2019-2023 by Featuremine Corporation.
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

name: 'Release action'
description: 'Change a github release draft option to false'
inputs:
  gh_token:
    description: 'Github token used to upload package'
    required: true
  pypi_token:
    description: 'Pypi token used to publish the wheels release'
    required: false
    default: ''
  destination:
    description: 'Destination repository to publish release'
    required: false
    default: ''
outputs:
  draft-check:
    description: 'Boolean to check if the release draft exists'
    value: ${{ steps.draft-check.outputs.draft }}
runs:
  using: 'composite'    
  steps:
  # Checkout to get the VERSION
  - uses: actions/checkout@v3.5.3
    with: 
      fetch-depth: 0

  - name: Install PyGitHub
    run: pip3 install PyGithub==1.58.0
    shell: bash

  - name: Check if draft exists
    id: draft-check
    env: 
      GH_TOKEN: ${{ inputs.gh_token }}
      GIT_MERGE_BASE: ${{ github.base_ref }}
      GIT_MERGE_HEAD: ${{ github.head_ref }}
      GIT_MERGE_COMMIT: ${{ github.sha }}
      GIT_REPO: ${{ github.repository }}
    run: |
      cp ${{github.action_path}}/draftcheck .
      python3 draftcheck
      rm draftcheck
    shell: bash

  - uses: nick-fields/retry@v2
    name: Publish
    if: steps.draft-check.outputs.draft == 'true' && github.event.pull_request.merged == true
    env: 
      GH_TOKEN: ${{ inputs.gh_token }}
    with:
      timeout_minutes: 5
      max_attempts: 5
      retry_wait_seconds: 1
      command: gh release edit v$(cat VERSION) --draft=false

  - uses: nick-fields/retry@v2
    name: Publish to destination
    if: steps.draft-check.outputs.draft == 'true' && github.event.pull_request.merged == true && inputs.destination != ''
    env: 
      GH_TOKEN: ${{ inputs.gh_token }}
    with:
      timeout_minutes: 5
      max_attempts: 5
      retry_wait_seconds: 1
      command: gh release edit v$(cat VERSION) --draft=false --repo ${{ inputs.destination }}

  - uses: nick-fields/retry@v2
    name: Download wheels
    if: inputs.pypi_token != '' && steps.draft-check.outputs.draft == 'true' && github.event.pull_request.merged == true
    env: 
      GH_TOKEN: ${{ inputs.gh_token }}
    with:
      timeout_minutes: 5
      max_attempts: 5
      retry_wait_seconds: 1
      command: gh release download v$(cat VERSION) --pattern '*.whl' --dir 'dist/'

  - name: Publish packages
    if: inputs.pypi_token != '' && steps.draft-check.outputs.draft == 'true' && github.event.pull_request.merged == true
    uses: pypa/gh-action-pypi-publish@release/v1
    with:
      user: __token__
      password: ${{ inputs.pypi_token }}
      skip_existing: true
      verbose: true
