name: 'Release action'
description: 'Change a github release draft option to false'
inputs:
  gh_token:
    description: 'Github token used to upload package'
    required: true
runs:
  using: 'composite'    
  steps:
  - uses: actions/checkout@main
    with: 
      fetch-depth: 0

  - name: Install PyGitHub
    run: pip3 install PyGithub
    shell: bash

  - name: Check if draft exists
    id: check-draft
    env: 
      GH_TOKEN: ${{ inputs.gh_token }}
      GIT_REPO: ${{ github.repository }}
    run: |
      cp ${{github.action_path}}/draftcheck .
      python3 draftcheck
      rm draftcheck
    shell: bash

  - name: Publish
    if: steps.check-draft.outputs.draft == 'true' && github.event.pull_request.merged == true
    env: 
      GH_TOKEN: ${{ inputs.gh_token }}
    run: gh release edit v$(cat VERSION) --draft=false
    shell: bash
