#!/usr/bin/env python3

"""
        COPYRIGHT (c) 2019-2023 by Featuremine Corporation.

        This Source Code Form is subject to the terms of the Mozilla Public
        License, v. 2.0. If a copy of the MPL was not distributed with this
        file, You can obtain one at https://mozilla.org/MPL/2.0/.
"""

import os
from os import path
from github import Github

ghrepo = Github(os.getenv('GH_TOKEN')).get_repo(os.getenv('GIT_REPO'))
 
if __name__ == '__main__':
    version =  list(open('VERSION'))[0].strip()
    
    draft = False
    print(f'GIT_MERGE_BASE is {os.getenv("GIT_MERGE_BASE")}')
    if os.getenv('GIT_MERGE_BASE') == 'main':
        for release in ghrepo.get_releases():
            if release.draft:
                if f"v{version}" == release.title:
                   draft = True

    if draft:
        print(f"matching draft found, need to publish the release {version}")
        with open(os.getenv('GITHUB_OUTPUT'), "a") as f:
            f.write("draft=true\n")
    else:
        print("either not merging into 'main' or no matching draft found; not publishing the release")
