#!/usr/bin/env python3

import os
from os import path
from github import Github

ghrepo = Github(os.getenv('GH_TOKEN')).get_repo(os.getenv('GIT_REPO'))

if __name__ == '__main__':
    version =  list(open('VERSION'))[0].strip()
    
    draft = False
    for release in ghrepo.get_releases():
        if release.draft:
            if f"v{version}" == release.title:
               draft = True

    if draft:
        print(f"matching draft found, need to publish the release {version}")
        print("::set-output name=draft::true")
    else:
        print("no matching draft found; not publishing the release")

    print(f"::set-output name=merge_base::{os.getenv('GIT_MERGE_BASE')}")
    